### ISSUE TITLE
User accounts

### ISSUE THREAD

**Issue by tjmonsi** [gdgphilippines/devfest2018#2]
- [ ] Login using Google, Github, Twitter, Facebook
- [ ] Logout
- [ ] For sponsors, ability to register to a sponsor company
- [ ] eventbrite ticket scanner and connector
- [ ] codelabs scoring system

Data structure
- name
- gender
- email 
- company
- city
- country

Separate: For Devfest Data structure of Users
- userId
  - eventbriteTicketId
  - sponsorBoothsRegistered
  - sponsorCompanyId (if sponsor)
  - codelab score
  - codelabIdsFinished

False on data rules: listing of users
