### ISSUE TITLE
Sponsors section

### ISSUE THREAD

**Issue by tjmonsi** [gdgphilippines/devfest2018#3]
- [ ] Sponsors list
- [ ] Sponsor  data object (created by sponsor)*
- [ ] Sponsor page (accessible only by sponsor)
- [ ] attendee list that registered under the "company"

Data structure
- Sponsor
  - Company name
  - Image of logo
  - URL
  - type of sponsor (let's ask adam on categories of sponsors)
  - accountIds
  - attendees (snapshot)

**Comment by tjmonsi** [comment]
Adding activity
